# Generated by Django 4.2 on 2023-05-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_user",
                    models.CharField(max_length=32, unique=True, verbose_name="账户名"),
                ),
                ("account_name", models.CharField(max_length=32, verbose_name="昵称")),
                (
                    "account_phone",
                    models.CharField(max_length=11, unique=True, verbose_name="电话号码"),
                ),
                (
                    "account_email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "account_password",
                    models.CharField(max_length=255, verbose_name="密码"),
                ),
                (
                    "account_type",
                    models.SmallIntegerField(
                        choices=[(0, "顾客"), (1, "管理员")], default=0, verbose_name="账户类型"
                    ),
                ),
                (
                    "account_status",
                    models.SmallIntegerField(
                        choices=[(0, "正常"), (1, "已封禁")], default=0, verbose_name="账户状态"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_idNumber",
                    models.CharField(max_length=18, verbose_name="身份证号"),
                ),
                ("customer_name", models.CharField(max_length=10, verbose_name="姓名")),
                (
                    "customer_phone",
                    models.CharField(max_length=11, verbose_name="电话号码"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="邮箱"),
                ),
                (
                    "customer_status",
                    models.SmallIntegerField(
                        choices=[(0, "正常"), (1, "已封禁")], default=0, verbose_name="状态"
                    ),
                ),
                (
                    "customer_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.account",
                        verbose_name="住客创建人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_idNumber", models.CharField(max_length=18, verbose_name="订单号")),
                (
                    "order_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="下单时间"),
                ),
                ("order_check_in", models.DateField(verbose_name="住房起始日期")),
                ("order_chenk_out", models.DateField(verbose_name="住房结束日期")),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[(0, "已预订"), (1, "已入住"), (2, "已退房")],
                        default=0,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="订单价格"
                    ),
                ),
                (
                    "order_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.account",
                        verbose_name="订单创建人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomType_name", models.CharField(max_length=10, verbose_name="房间类型")),
                (
                    "roomType_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="房间价格"
                    ),
                ),
                (
                    "roomType_description",
                    models.TextField(blank=True, null=True, verbose_name="房间描述"),
                ),
                (
                    "roomType_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="static/img/rooms/",
                        verbose_name="房间图片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=10, unique=True, verbose_name="房间号"),
                ),
                (
                    "room_status",
                    models.SmallIntegerField(
                        choices=[(0, "空闲"), (1, "已预订"), (2, "已入住")],
                        default=0,
                        verbose_name="房间状态",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotel.roomtype",
                        verbose_name="房间类型",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.customer",
                        verbose_name="顾客",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.room",
                        verbose_name="房间",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="order_rooms",
            field=models.ManyToManyField(
                through="hotel.OrderDetail", to="hotel.room", verbose_name="订单房间"
            ),
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_title", models.CharField(max_length=40, verbose_name="通知标题")),
                (
                    "notice_content",
                    models.TextField(max_length=300, verbose_name="通知内容"),
                ),
                (
                    "notice_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                ("notice_expiration", models.DateTimeField(verbose_name="失效时间")),
                (
                    "notice_publisher",
                    models.ForeignKey(
                        limit_choices_to={"account_type": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.account",
                        verbose_name="发布人",
                    ),
                ),
            ],
        ),
    ]
