# Generated by Django 4.2 on 2023-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="OrderCustomerRoom", new_name="OrderDetail",),
        migrations.RenameField(
            model_name="order", old_name="order_start_time", new_name="order_check_in",
        ),
        migrations.RenameField(
            model_name="order", old_name="order_end_time", new_name="order_chenk_out",
        ),
        migrations.AddField(
            model_name="order",
            name="order_rooms",
            field=models.ManyToManyField(
                through="hotel.OrderDetail", to="hotel.room", verbose_name="订单房间"
            ),
        ),
    ]
