# Generated by Django 4.2 on 2023-05-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_room",),
    ]
