# Generated by Django 4.2 on 2023-05-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_remove_order_order_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="notice_publisher",
            field=models.ForeignKey(
                limit_choices_to={"account_type": 1},
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel.account",
                verbose_name="发布人",
            ),
        ),
    ]
