# Generated by Django 4.2 on 2023-05-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_rename_ordercustomerroom_orderdetail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="roomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomType_name", models.CharField(max_length=10, verbose_name="房间类型")),
                (
                    "roomType_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="房间价格"
                    ),
                ),
                ("roomType_description", models.TextField(verbose_name="房间描述")),
                (
                    "roomType_img",
                    models.ImageField(
                        upload_to="static/img/rooms/", verbose_name="房间图片"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="room", name="room_description",),
        migrations.RemoveField(model_name="room", name="room_img",),
        migrations.RemoveField(model_name="room", name="room_price",),
        migrations.AlterField(
            model_name="account",
            name="account_email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_phone",
            field=models.CharField(max_length=11, unique=True, verbose_name="电话号码"),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_user",
            field=models.CharField(max_length=32, unique=True, verbose_name="账户名"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=10, unique=True, verbose_name="房间号"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.roomtype",
                verbose_name="房间类型",
            ),
        ),
    ]
