# Generated by Django 4.2 on 2023-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_roomtype_remove_room_room_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="roomType_description",
            field=models.TextField(blank=True, null=True, verbose_name="房间描述"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="roomType_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/img/rooms/",
                verbose_name="房间图片",
            ),
        ),
    ]
